#!/sbin/openrc-run

: ${command_args:="run"}
: ${user:="gitlab-runner"}
: ${logfile:="/var/log/$RC_SVCNAME.log"}
: ${datadir:="/var/lib/gitlab-runner"}

command="/usr/bin/gitlab-runner"
command_background="yes"

pidfile="/run/$RC_SVCNAME.pid"
start_stop_daemon_args="
	--user $user
	--chdir '$datadir'
	--stdout '$logfile'
	--stderr '$logfile'"

depend() {
	after sshd
	need localmount net
}

start_pre() {
	checkpath -f -m 644 -o $user "$logfile"
}
