#!/bin/sh
set -eu

GLR_USER="${GLR_USER:-gitlab-runner}"

if [ "$(id -un)" != "$GLR_USER" ]; then
	exec su "$GLR_USER" -s /bin/sh -c '"$0" "$@"' -- /usr/bin/gitlab-runner "$@"
else
	exec /usr/bin/gitlab-runner "$@"
fi
