#!/bin/sh
set -eu

export VIRTUAL_ENV='/usr/lib/bundles/devpi-server'

DEVPI_USER="${DEVPI_USER:-devpi}"
COMMAND="$VIRTUAL_ENV/bin/$(basename "$0")"

if [ "$(id -un)" != "$DEVPI_USER" ]; then
	exec su "$DEVPI_USER" -s /bin/sh -c '"$0" "$@"' -- $COMMAND "$@"
else
	exec $COMMAND "$@"
fi
