#!/sbin/openrc-run

: ${command_args:="run"}
: ${user:="gitlab-runner"}
: ${logfile:="/var/log/gitlab-ci-runner/$RC_SVCNAME.log"}
: ${datadir:="/var/lib/gitlab-ci-runner"}

command="/usr/bin/gitlab-ci-multi-runner"
command_background="yes"

pidfile="/run/$RC_SVCNAME.pid"
start_stop_daemon_args="
	--user $user
	--chdir '$datadir'
	--stdout '$logfile'
	--stderr '$logfile'"

depend() {
	after sshd
	need localmount net
}
