#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

APK_TOOLS_URI='https://github.com/alpinelinux/apk-tools/releases/download/v2.10.4/apk-tools-2.10.4-x86_64-linux.tar.gz'
APK_TOOLS_SHA256='efe948160317fe78058e207554d0d9195a3dfcc35f77df278d30448d7b3eb892'

echo '\n==> Downloading apk-tools-static'

cd /tmp
wget -T 10 "$APK_TOOLS_URI"
echo "$APK_TOOLS_SHA256  ${APK_TOOLS_URI##*/}" | sha256sum -c
tar -xzf ${APK_TOOLS_URI##*/}
mv apk-tools-*/apk apk


echo '\n==> Installing Alpine Linux'

mkdir -p "$ALPINE_ROOT"/etc/apk
cd "$ALPINE_ROOT"

cp -R "$CLONE_DIR"/.keys etc/apk/keys
cp "$CLONE_DIR"/.travis/repositories etc/apk/repositories
cp /etc/resolv.conf etc/resolv.conf

/tmp/apk \
	--root . --update-cache --initdb --no-progress \
	add alpine-base

mount -t proc none proc
mount --rbind /sys sys
mount --rbind /dev dev
