#!/bin/sh
set -e

printf 'Enter new password for the admin user: '
read -s pass
printf '\n'
[ "$pass" ] || exit 1

hash=$(printf "$pass" | sha256sum | cut -d ' ' -f1)
sed -i "s|^#*\(root_password_sha2\s*=\).*|\1 $hash|" \
	/etc/graylog/server/server.conf
