#!/bin/sh
# This script is supposed to be executed by cron.
set -eu

# Option pipefail is not specified by POSIX and not supported e.g. by dash.
# However, running this script without pipefail would be unsafe.
if ( set -o pipefail 2>/dev/null ); then
	set -o pipefail
else
	echo 'healthchecks-prune: Your shell does not support option pipefail!' >&2
	exit 1
fi

case "$1" in -h | --help | help)
	cat >&2 <<-EOF
		Usage: $0 [options]

		Run Healthchecks' tasks prunepingsslow, prunechecks and prunenotifications
		and logs to syslog.
		Options are passed into healthchecks-manage executed for each task.
	EOF
	exit 0
esac

{
	/usr/bin/healthchecks-manage prunepingsslow "$@"
	/usr/bin/healthchecks-manage prunechecks "$@"
	/usr/bin/healthchecks-manage prunenotifications "$@"
} 2>&1 | logger -s -t 'healthchecks-prune' -p 'cron.info'
