#!/bin/sh
# This script is supposed to be executed by cron.
set -eu

PROGNAME='healthchecks-prune'

# Option pipefail is not specified by POSIX and not supported e.g. by dash.
# However, running this script without pipefail would be unsafe.
if ( set -o pipefail 2>/dev/null ); then
	set -o pipefail
else
	echo "$PROGNAME: Your shell does not support option pipefail!" >&2
	exit 1
fi

case "${1:-}" in -h | --help | help)
	cat >&2 <<-EOF
		Usage: $0 [options]

		Run Healthchecks' tasks prunepingsslow, prunechecks and prunenotifications
		and logs to syslog.
		Options are passed into healthchecks-manage executed for each task.
	EOF
	exit 0
esac

{
	rc=0
	/usr/bin/healthchecks-manage prunepings "$@" || rc=2
	/usr/bin/healthchecks-manage prunenotifications "$@" || rc=2
	/usr/bin/healthchecks-manage prunetokenbucket "$@" || rc=2
	/usr/bin/healthchecks-manage pruneflips "$@" || rc=2
	return $rc
} 2>&1 | logger -s -t "$PROGNAME" -p 'cron.info'
